<a href="https://colab.research.google.com/github/vietdai-bk/machine_learning_course/blob/main/MachineLearningBasic_Week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lí thuyết về Machine Learning

## 1. Giới Thiệu

### 1.1. Machine Learning (ML) là gì? Supervised vs Unsupervised vs Reinforcement Learning
- **Machine Learning (ML)** là một nhánh của trí tuệ nhân tạo (AI), tập trung vào việc phát triển các thuật toán cho phép máy tính học hỏi từ dữ liệu mà không cần lập trình rõ ràng cho từng nhiệm vụ.
- **Supervised Learning (Học có giám sát):** Là phương pháp mà mô hình được huấn luyện trên tập dữ liệu có nhãn (labeled data), bao gồm đầu vào (input) và đầu ra mong muốn (output). Ví dụ: Phân loại (classification) và hồi quy (regression).
- **Unsupervised Learning (Học không giám sát):** Là phương pháp mà mô hình làm việc với dữ liệu không có nhãn, nhằm tìm ra cấu trúc hoặc mẫu ẩn trong dữ liệu. Ví dụ: Phân cụm (clustering) và giảm chiều dữ liệu (dimensionality reduction).
- **Reinforcement Learning (Học tăng cường):** Là phương pháp mà một tác nhân (agent) học cách đưa ra quyết định bằng cách tương tác với môi trường, nhận phần thưởng (reward) hoặc hình phạt (penalty) dựa trên hành động. Ví dụ: Đào tạo AI chơi game hoặc robot tự động điều hướng.
### 1.2. Các thư viện python quan trọng cho Machine Learning
- **NumPy:** Thư viện cơ bản cho tính toán số học, hỗ trợ mảng đa chiều (arrays).
- **Pandas:** Thư viện mạnh mẽ để xử lý và phân tích dữ liệu với cấu trúc DataFrame.
- **Matplotlib:** Thư viện trực quan hóa dữ liệu, vẽ biểu đồ 2D.
- **Seaborn:** Xây dựng trên Matplotlib, cung cấp giao diện trực quan hóa thống kê đẹp mắt.
- **Scikit-Learn:** Thư viện học máy phổ biến, có sẵn một vài tập datasets, hỗ trợ phân loại, hồi quy, gom cụm.

# Các phương thức trong các thư viện cần biết
Dưới đây là danh sách các phương thức quan trọng trong các thư viện **NumPy**, **Pandas**, **Matplotlib**, **Seaborn**, và **Scikit-Learn**, được sắp xếp theo mục đích sử dụng trong quy trình Machine Learning.

---

## 1. NumPy
Thư viện **NumPy** được dùng để xử lý mảng đa chiều và tính toán số học, là nền tảng cho các phép toán trong ML.

### 1.1. Tạo và thao tác với mảng
- `np.array(list)`: Tạo mảng NumPy từ list.
- `np.zeros(shape)`: Tạo mảng toàn số 0 với kích thước `shape`.
- `np.ones(shape)`: Tạo mảng toàn số 1 với kích thước `shape`.
- `np.arange(start, stop, step)`: Tạo mảng với dãy số từ `start` đến `stop`, bước nhảy `step`.
- `np.linspace(start, stop, num)`: Tạo mảng với `num` giá trị cách đều nhau từ `start` đến `stop`.
- `np.random.rand(shape)`: Tạo mảng với các giá trị ngẫu nhiên từ 0 đến 1.
- `np.random.randint(low, high, size)`: Tạo mảng với các số nguyên ngẫu nhiên từ `low` đến `high`.

### 1.2. Thao tác trên mảng
- `array.reshape(shape)`: Thay đổi hình dạng của mảng.
- `array.T`: Chuyển vị mảng (transpose).
- `np.concatenate((array1, array2), axis)`: Ghép hai mảng theo trục `axis`.
- `np.vstack((array1, array2))`: Ghép hai mảng theo chiều dọc.
- `np.hstack((array1, array2))`: Ghép hai mảng theo chiều ngang.
- `np.split(array, indices_or_sections)`: Chia mảng thành nhiều phần.

### 1.3. Tính toán số học
- `np.sum(array, axis)`: Tính tổng các phần tử trong mảng theo trục `axis`.
- `np.mean(array, axis)`: Tính trung bình các phần tử.
- `np.std(array, axis)`: Tính độ lệch chuẩn.
- `np.min(array)`, `np.max(array)`: Tìm giá trị nhỏ nhất/lớn nhất.
- `np.dot(array1, array2)`: Tích vô hướng giữa hai mảng.
- `np.linalg.inv(array)`: Tính ma trận nghịch đảo.

---

## 2. Pandas
Thư viện **Pandas** được dùng để xử lý và phân tích dữ liệu, đặc biệt với cấu trúc **DataFrame**.

### 2.1. Tạo và đọc dữ liệu
- `pd.DataFrame(data)`: Tạo DataFrame từ dữ liệu (list, dict, mảng NumPy, v.v.).
- `pd.read_csv(file_path)`: Đọc file CSV vào DataFrame.
- `pd.read_excel(file_path)`: Đọc file Excel vào DataFrame.
- `df.to_csv(file_path)`: Xuất DataFrame ra file CSV.

### 2.2. Khám phá dữ liệu
- `df.head(n)`: Xem `n` dòng đầu của DataFrame (mặc định là 5).
- `df.tail(n)`: Xem `n` dòng cuối của DataFrame.
- `df.info()`: Hiển thị thông tin tổng quan (cột, kiểu dữ liệu, giá trị null).
- `df.describe()`: Thống kê cơ bản (mean, std, min, max, v.v.).
- `df.shape`: Kích thước của DataFrame (số dòng, số cột).
- `df.columns`: Lấy danh sách tên cột.
- `df.dtypes`: Kiểm tra kiểu dữ liệu của từng cột.

### 2.3. Làm sạch dữ liệu
- `df.drop(columns=[col1, col2])`: Xóa cột khỏi DataFrame.
- `df.dropna()`: Xóa các dòng chứa giá trị `NaN`.
- `df.fillna(value)`: Thay thế `NaN` bằng `value`.
- `df.duplicated()`: Kiểm tra các dòng trùng lặp.
- `df.drop_duplicates()`: Xóa các dòng trùng lặp.
- `df.rename(columns={old: new})`: Đổi tên cột.

### 2.4. Lọc và truy vấn dữ liệu
- `df[col]`: Lấy cột `col` dưới dạng Series.
- `df[[col1, col2]]`: Lấy nhiều cột dưới dạng DataFrame.
- `df.iloc[row_idx, col_idx]`: Truy cập dữ liệu theo chỉ số.
- `df.loc[row_label, col_label]`: Truy cập dữ liệu theo nhãn.
- `df[df[col] > value]`: Lọc dữ liệu dựa trên điều kiện.
- `df.groupby(col)`: Nhóm dữ liệu theo cột `col`.
- `df.merge(df2, on=col)`: Kết hợp hai DataFrame dựa trên cột `col`.

---

## 3. Matplotlib
Thư viện **Matplotlib** được dùng để trực quan hóa dữ liệu, giúp hiểu rõ hơn về dữ liệu trong ML.

### 3.1. Cài đặt và khởi tạo
- `plt.figure(figsize=(width, height))`: Tạo một figure với kích thước xác định.
- `plt.subplot(nrows, ncols, index)`: Tạo nhiều biểu đồ trong cùng một figure.

### 3.2. Vẽ các loại biểu đồ
- `plt.plot(x, y, label='')`: Vẽ biểu đồ đường.
- `plt.scatter(x, y)`: Vẽ biểu đồ phân tán.
- `plt.bar(x, height)`: Vẽ biểu đồ cột.
- `plt.hist(data, bins)`: Vẽ histogram.
- `plt.boxplot(data)`: Vẽ biểu đồ hộp (boxplot).

### 3.3. Tùy chỉnh biểu đồ
- `plt.title('Tiêu đề')`: Đặt tiêu đề cho biểu đồ.
- `plt.xlabel('Tên trục x')`, `plt.ylabel('Tên trục y')`: Đặt nhãn cho trục.
- `plt.legend()`: Hiển thị chú thích (dựa trên `label` trong `plot`).
- `plt.grid(True)`: Hiển thị lưới.
- `plt.xticks()`, `plt.yticks()`: Tùy chỉnh các điểm trên trục.
- `plt.show()`: Hiển thị biểu đồ.

---

## 4. Seaborn
Thư viện **Seaborn** xây dựng trên Matplotlib, cung cấp các biểu đồ thống kê đẹp mắt.

### 4.1. Vẽ biểu đồ thống kê
- `sns.scatterplot(x, y, data=df)`: Biểu đồ phân tán.
- `sns.lineplot(x, y, data=df)`: Biểu đồ đường.
- `sns.histplot(data, bins)`: Histogram.
- `sns.boxplot(x, y, data=df)`: Biểu đồ hộp.
- `sns.heatmap(data, annot=True)`: Biểu đồ nhiệt (heatmap) để trực quan hóa ma trận tương quan.
- `sns.pairplot(df)`: Vẽ ma trận biểu đồ phân tán cho tất cả các cặp biến.

### 4.2. Tùy chỉnh giao diện
- `sns.set_style('style')`: Đặt phong cách biểu đồ (ví dụ: `darkgrid`, `whitegrid`).
- `sns.color_palette()`: Tùy chỉnh bảng màu.

---

## 5. Scikit-Learn
Thư viện **Scikit-Learn** cung cấp các công cụ để xây dựng, huấn luyện và đánh giá mô hình ML.

### 5.1. Tiền xử lý dữ liệu
- `preprocessing.StandardScaler()`: Chuẩn hóa dữ liệu (z-score normalization).
  - `scaler.fit_transform(X)`: Chuẩn hóa dữ liệu.
- `preprocessing.MinMaxScaler()`: Chuẩn hóa dữ liệu về khoảng [0, 1].
- `preprocessing.LabelEncoder()`: Chuyển đổi nhãn dạng chuỗi thành số.
- `preprocessing.OneHotEncoder()`: Mã hóa biến phân loại thành dạng one-hot.
- `train_test_split(X, y, test_size, random_state)`: Chia dữ liệu thành tập huấn luyện và kiểm tra.

### 5.2. Tải dataset mẫu
- `datasets.load_iris()`: Tải dataset Iris.
- `datasets.load_digits()`: Tải dataset Digits.
- `datasets.load_breast_cancer()`: Tải dataset Breast Cancer.

### 5.3. Các mô hình học máy
- **Phân loại (Classification):**
  - `LinearRegression()`: Hồi quy tuyến tính.
  - `LogisticRegression()`: Hồi quy logistic.
  - `KNeighborsClassifier()`: K-Nearest Neighbors.
  - `DecisionTreeClassifier()`: Cây quyết định.
  - `RandomForestClassifier()`: Rừng ngẫu nhiên.
  - `SVC()`: Support Vector Classifier.
- **Hồi quy (Regression):**
  - `LinearRegression()`: Hồi quy tuyến tính.
  - `Ridge()`, `Lasso()`: Hồi quy với điều chuẩn.
  - `RandomForestRegressor()`: Rừng ngẫu nhiên cho hồi quy.
- **Gom cụm (Clustering):**
  - `KMeans(n_clusters)`: Gom cụm K-Means.
  - `DBSCAN()`: Gom cụm dựa trên mật độ.
- **Giảm chiều (Dimensionality Reduction):**
  - `PCA(n_components)`: Phân tích thành phần chính (PCA).
  - `TSNE()`: T-SNE để trực quan hóa dữ liệu.

### 5.4. Huấn luyện và dự đoán
- `model.fit(X_train, y_train)`: Huấn luyện mô hình.
- `model.predict(X_test)`: Dự đoán trên tập dữ liệu mới.
- `model.score(X_test, y_test)`: Đánh giá độ chính xác (cho phân loại) hoặc R² (cho hồi quy).

### 5.5. Đánh giá mô hình
- `metrics.accuracy_score(y_true, y_pred)`: Tính độ chính xác cho phân loại.
- `metrics.precision_score()`, `metrics.recall_score()`, `metrics.f1_score()`: Tính precision, recall, F1-score.
- `metrics.confusion_matrix(y_true, y_pred)`: Tạo ma trận nhầm lẫn.
- `metrics.mean_squared_error(y_true, y_pred)`: Tính sai số bình phương trung bình (MSE).
- `metrics.r2_score(y_true, y_pred)`: Tính hệ số R².

### 5.6. Tối ưu mô hình
- `model_selection.GridSearchCV(estimator, param_grid)`: Tìm kiếm tham số tối ưu bằng lưới.
- `model_selection.cross_val_score(model, X, y, cv)`: Thực hiện kiểm định chéo (cross-validation).

# Tài liệu tham khảo cho các thư viện

Dưới đây là các liên kết đến tài liệu chính thức của các thư viện được sử dụng trong Machine Learning:

- **[NumPy Documentation](https://numpy.org/doc/stable/)**  
  Tài liệu chính thức của NumPy, cung cấp thông tin chi tiết về các hàm, mảng, và tính toán số học.

- **[Pandas Documentation](https://pandas.pydata.org/docs/)**  
  Tài liệu chính thức của Pandas, bao gồm hướng dẫn về DataFrame, Series, và các phương thức xử lý dữ liệu.

- **[Matplotlib Documentation](https://matplotlib.org/stable/contents.html)**  
  Tài liệu chính thức của Matplotlib, cung cấp thông tin về các loại biểu đồ và tùy chỉnh trực quan hóa.

- **[Seaborn Documentation](https://seaborn.pydata.org/)**  
  Tài liệu chính thức của Seaborn, tập trung vào các biểu đồ thống kê và giao diện đẹp mắt dựa trên Matplotlib.

- **[Scikit-Learn Documentation](https://scikit-learn.org/stable/)**  
  Tài liệu chính thức của Scikit-Learn, bao gồm các thuật toán học máy, tiền xử lý dữ liệu, và đánh giá mô hình.

# Bài tập thực hành với các thư viện Machine Learning

Dưới đây là các bài tập thực hành cho từng thư viện **NumPy**, **Pandas**, **Matplotlib**, **Seaborn**, và **Scikit-Learn**.

---

## 1. Bài tập với NumPy
NumPy được dùng để xử lý mảng và tính toán số học, là nền tảng cho các phép toán trong ML.

### Bài 1: Tạo và thao tác mảng
- **Yêu cầu:** Tạo một mảng 2D kích thước 3x4 với các giá trị ngẫu nhiên từ 1 đến 10, sau đó:
  1. In mảng.
  2. Tính tổng các phần tử trong mảng.
  3. Chuyển vị mảng và in kết quả.

### Bài 2: Tính toán thống kê
- **Yêu cầu:** Tạo một mảng 1D với 20 giá trị ngẫu nhiên từ 0 đến 100, sau đó:
  1. Tính trung bình, độ lệch chuẩn, giá trị lớn nhất, và nhỏ nhất.
  2. Chuẩn hóa mảng về khoảng [0, 1] (dùng công thức: `(x - min) / (max - min)`).

### Bài 3: Ghép và chia mảng
- **Yêu cầu:** Tạo hai mảng 1D với 5 giá trị ngẫu nhiên từ 1 đến 10, sau đó:
  1. Ghép hai mảng theo chiều ngang và in kết quả.
  2. Chia mảng kết quả thành 2 phần bằng nhau và in.

---

## 2. Bài tập với Pandas
Pandas được dùng để xử lý và phân tích dữ liệu.

### Bài 4: Khám phá dữ liệu
- **Yêu cầu:** Tải dataset mẫu từ Scikit-Learn (ví dụ: `load_iris`), chuyển thành DataFrame, sau đó:
  1. In 5 dòng đầu và 5 dòng cuối.
  2. Hiển thị thông tin tổng quan và thống kê cơ bản.
  3. Kiểm tra xem có giá trị `NaN` nào không.

### Bài 5: Làm sạch dữ liệu
- **Yêu cầu:** Tạo một DataFrame với dữ liệu giả lập chứa giá trị `NaN` và trùng lặp, sau đó:
  1. Xóa các dòng chứa `NaN`.
  2. Xóa các dòng trùng lặp.
  3. Đổi tên cột đầu tiên thành "Feature_1".

### Bài 6: Lọc và nhóm dữ liệu
- **Yêu cầu:** Sử dụng dataset Iris từ Scikit-Learn, sau đó:
  1. Lọc các dòng có giá trị cột đầu tiên lớn hơn trung bình.
  2. Nhóm dữ liệu theo cột nhãn (`target`) và tính trung bình của các cột.

---

## 3. Bài tập với Matplotlib
Matplotlib được dùng để trực quan hóa dữ liệu.

### Bài 7: Vẽ biểu đồ cơ bản
- **Yêu cầu:** Tạo dữ liệu giả lập với 10 điểm (x từ 0 đến 9, y là giá trị ngẫu nhiên từ 1 đến 10), sau đó:
  1. Vẽ biểu đồ đường và biểu đồ phân tán trên cùng một figure.
  2. Thêm tiêu đề, nhãn trục, và chú thích.
- **Hướng dẫn:** Sử dụng `plt.plot()`, `plt.scatter()`, `title()`, `xlabel()`, `ylabel()`, và `legend()`.

### Bài 8: Vẽ nhiều biểu đồ
- **Yêu cầu:** Sử dụng dataset Iris, vẽ 4 biểu đồ histogram cho 4 cột dữ liệu trên cùng một figure (sử dụng subplot).
- **Hướng dẫn:** Sử dụng `plt.subplot()` và `plt.hist()`.

### Bài 9: Vẽ biểu đồ hộp
- **Yêu cầu:** Sử dụng dataset Iris, vẽ biểu đồ hộp (boxplot) cho cột đầu tiên của dữ liệu.
- **Hướng dẫn:** Sử dụng `plt.boxplot()`.

---

## 4. Bài tập với Seaborn
Seaborn cung cấp các biểu đồ thống kê đẹp mắt.

### Bài 10: Vẽ biểu đồ phân tán và heatmap
- **Yêu cầu:** Sử dụng dataset Iris, sau đó:
  1. Vẽ biểu đồ phân tán giữa hai cột đầu tiên, với màu sắc khác nhau theo nhãn (`target`).
  2. Vẽ heatmap của ma trận tương quan giữa các cột.
- **Hướng dẫn:** Sử dụng `sns.scatterplot()` và `sns.heatmap()`.

### Bài 11: Vẽ pairplot
- **Yêu cầu:** Sử dụng dataset Iris, vẽ ma trận biểu đồ phân tán (pairplot) cho tất cả các cột, với màu sắc khác nhau theo nhãn.
- **Hướng dẫn:** Sử dụng `sns.pairplot()`.

### Bài 12: Vẽ boxplot
- **Yêu cầu:** Sử dụng dataset Iris, vẽ boxplot của cột đầu tiên, phân chia theo nhãn (`target`).
- **Hướng dẫn:** Sử dụng `sns.boxplot()`.

---

## 5. Bài tập với Scikit-Learn
Scikit-Learn được dùng để xây dựng và đánh giá mô hình ML.

### Bài 13: Tiền xử lý và chia dữ liệu
- **Yêu cầu:** Sử dụng dataset Iris, sau đó:
  1. Chuẩn hóa dữ liệu bằng `StandardScaler`.
  2. Chia dữ liệu thành tập huấn luyện (80%) và kiểm tra (20%).
- **Hướng dẫn:** Sử dụng `preprocessing.StandardScaler()` và `train_test_split()`.

### Bài 14: Xây dựng và đánh giá mô hình
- **Yêu cầu:** Sử dụng dataset Iris, xây dựng mô hình phân loại với `RandomForestClassifier`, sau đó:
  1. Huấn luyện mô hình trên tập huấn luyện.
  2. Dự đoán trên tập kiểm tra.
  3. Tính độ chính xác và ma trận nhầm lẫn.
- **Hướng dẫn:** Sử dụng `RandomForestClassifier()`, `fit()`, `predict()`, `accuracy_score()`, và `confusion_matrix()`.

### Bài 15: Gom cụm và giảm chiều
- **Yêu cầu:** Sử dụng dataset Iris, sau đó:
  1. Áp dụng K-Means để gom cụm dữ liệu thành 3 cụm.
  2. Giảm chiều dữ liệu xuống 2D bằng PCA và vẽ biểu đồ phân tán của dữ liệu sau giảm chiều, với màu sắc theo cụm.
- **Hướng dẫn:** Sử dụng `KMeans()`, `PCA()`, và `plt.scatter()`.

# Giải

### Bài 1:
- **Yêu cầu:** Tạo một mảng 2D kích thước 3x4 với các giá trị ngẫu nhiên từ 1 đến 10, sau đó:
  1. In mảng.
  2. Tính tổng các phần tử trong mảng.
  3. Chuyển vị mảng và in kết quả.
  - **Hướng dẫn:** Sử dụng `np.random.randint()`, `np.sum()`, và `.T`.

In [ ]:
import numpy as np
np_arr = np.random.randint(1, 11, [3,4]) ## tạo mảng ngẫu nhiên với mỗi phần tử 0<=x<11, size = 3x4
print(np_arr)
## Tính tổng dùng np.sum()
print(np.sum(np_arr))
## Chuyển vị mảng dùng .T
np_arrT = np_arr.T
print(np_arrT)

[[3 2 5 7]
 [9 7 7 1]
 [1 6 6 3]]
57
[[3 9 1]
 [2 7 6]
 [5 7 6]
 [7 1 3]]


### Bài 2:
- **Yêu cầu:** Tạo một mảng 1D với 20 giá trị ngẫu nhiên từ 0 đến 100, sau đó:
  1. Tính trung bình, độ lệch chuẩn, giá trị lớn nhất, và nhỏ nhất.
  2. Chuẩn hóa mảng về khoảng [0, 1] (dùng công thức:
  $x_{\text{scaled}} = \frac{x - x_{\text{min}}}{x_{\text{max}} - x_{\text{min}}}$)

  - **Hướng dẫn:** Sử dụng `np.random.randint()`, `np.mean()`, `np.std()`, `np.min()`, `np.max()`.
  
  Chuẩn hóa về cùng một khoảng [0,1], khi $x = {x_\text{min}}$ thì $x_{\text{scaled} = 0}$, $x = {x_\text{max}}$ thì $x_{\text{scaled} = 1}$ còn với các giá trị khác của x thì $x_\text{scaled} \in [0,1]$.

  Công thức mở rộng để chuẩn hóa về khoảng [$a, b$] là:  
$$x_{\text{scaled}} = a + \frac{(x - x_{\text{min}}) \cdot (b - a)}{x_{\text{max}} - x_{\text{min}}}$$

In [ ]:
import numpy as np

np_arr = np.random.randint(0, 101, 20) ## Tạo mảng 1x20
print(np_arr)

## Tính trung bình
mean = np.mean(np_arr)
print(mean)

## Tính độ lệch chuẩn
std = np.std(np_arr)
print(std)

## Tính min và max trong mảng
min = np.min(np_arr)
max = np.max(np_arr)
print(min, max)

## Chuẩn hóa mảng về 0 1
normalization_arr = np.array([(x-min)/(max-min) for x in np_arr])
print(normalization_arr)

[96 33  7 46 85 73 97  1 30  1 88 47 25 55 66  0 95 72 22 71]
50.5
33.18358027699844
0 97
[0.98969072 0.34020619 0.07216495 0.4742268  0.87628866 0.75257732
 1.         0.01030928 0.30927835 0.01030928 0.90721649 0.48453608
 0.25773196 0.56701031 0.68041237 0.         0.97938144 0.74226804
 0.22680412 0.73195876]


### Bài 3:
- **Yêu cầu:** Tạo hai mảng 1D với 5 giá trị ngẫu nhiên từ 1 đến 10, sau đó:
  1. Ghép hai mảng theo chiều ngang và in kết quả.
  2. Chia mảng kết quả thành 2 phần bằng nhau và in.
  - **Hướng dẫn:** Sử dụng `np.hstack()` và `np.split()`.

  Ghép mảng theo chiều ngang, ví dụ có 2 mảng
\begin{pmatrix}
a1 & b1 & c1 & d1
\end{pmatrix}
 và
\begin{pmatrix}
a2 & b2 & c2 & d2
\end{pmatrix}
sau khi ghép theo **chiều ngang**
\begin{pmatrix}
a1 & b1 & c1 & d1 & a2 & b2 & c2 & d2
\end{pmatrix}
  **chiều dọc** thì
\begin{pmatrix}
a1 & b1 & c1 & d1 \\
a2 & b2 & c2 & d2
\end{pmatrix}

In [ ]:
import numpy

arr_1 = np.random.randint(1, 11, 5)
arr_2 = np.random.randint(1, 11, 5)
print(arr_1, arr_2)

arr = np.hstack((arr_1, arr_2)) ## Ghép mảng theo chiều dọc
print(arr)

arr_split1, arr_split2 = np.split(arr, 2) ## Chia mảng thành 2 phần bằng nhau, lưu ý số phần tử trong mảng phải chia hết cho số phần định chia
print(arr_split1, arr_split2)

[ 1  5 10  3  3] [10  3  2 10  5]
[ 1  5 10  3  3 10  3  2 10  5]
[ 1  5 10  3  3] [10  3  2 10  5]


### Bài 4:
- **Yêu cầu:** Tải dataset mẫu từ Scikit-Learn (ví dụ: `load_iris`), chuyển thành DataFrame, sau đó:
  1. In 5 dòng đầu và 5 dòng cuối.
  2. Hiển thị thông tin tổng quan và thống kê cơ bản.
  3. Kiểm tra xem có giá trị `NaN` nào không.
- **Hướng dẫn:** Sử dụng `pd.DataFrame()`, `head()`, `tail()`, `info()`, `describe()`, và `isna()`.

In [ ]:
## Cài thư viện scikit-learn
!pip install scikit-learn ## Lưu ý import dùng sklearn

In [ ]:
from sklearn import datasets
import pandas as pd

iris = datasets.load_iris()
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df.head() ## In 5 dòng đầu

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
iris_df.tail() ## In 5 dòng cuối

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [ ]:
## Hiển thị thông tin tổng quan
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [ ]:
iris_df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [ ]:
iris_df.isna() ## Từ info() cũng có thể biết được là trong datasets không có ô nào là NaN

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                False             False              False             False
1                False             False              False             False
2                False             False              False             False
3                False             False              False             False
4                False             False              False             False
..                 ...               ...                ...               ...
145              False             False              False             False
146              False             False              False             False
147              False             False              False             False
148              False             False              False             False
149              False             False              False             False

[150 rows x 4 columns]

### Bài 5:
- **Yêu cầu:** Tạo một DataFrame với dữ liệu giả lập chứa giá trị `NaN` và trùng lặp, sau đó:
  1. Xóa các dòng chứa `NaN`.
  2. Xóa các dòng trùng lặp.
  3. Đổi tên cột đầu tiên thành "Feature_1".
- **Hướng dẫn:** Sử dụng `dropna()`, `drop_duplicates()`, và `rename()`.

In [ ]:
import pandas as pd

data = {
    'A': [1, 2, np.nan, 4, 5, 1, 1],
    'B': [np.nan, 2, 3, np.nan, 5, 1, 1],
    'C': [1, 2, 3, 4, 5, 1, 1],
    'D': [np.nan, np.nan, 3, 4, 5, 1, 1]
}

df = pd.DataFrame(data)
df

A    B  C    D
0  1.0  NaN  1  NaN
1  2.0  2.0  2  NaN
2  NaN  3.0  3  3.0
3  4.0  NaN  4  4.0
4  5.0  5.0  5  5.0
5  1.0  1.0  1  1.0
6  1.0  1.0  1  1.0

In [ ]:
df.dropna() ## Xóa các dòng chứa NaN, này chỉ in ra kết quả sau khi xóa, không hoàn toàn xóa

A    B  C    D
4  5.0  5.0  5  5.0
5  1.0  1.0  1  1.0
6  1.0  1.0  1  1.0

In [ ]:
df.drop_duplicates() ## Xóa các dòng trùng lặp, này chỉ in ra kết quả sau khi xóa, không hoàn toàn xóa

A    B  C    D
0  1.0  NaN  1  NaN
1  2.0  2.0  2  NaN
2  NaN  3.0  3  3.0
3  4.0  NaN  4  4.0
4  5.0  5.0  5  5.0
5  1.0  1.0  1  1.0

In [ ]:
df.rename(columns={'A': 'Feature_1'}) ## Đổi tên cột A thành Feature_1

Feature_1    B  C    D
0        1.0  NaN  1  NaN
1        2.0  2.0  2  NaN
2        NaN  3.0  3  3.0
3        4.0  NaN  4  4.0
4        5.0  5.0  5  5.0
5        1.0  1.0  1  1.0
6        1.0  1.0  1  1.0

### Bài 6:
- **Yêu cầu:** Sử dụng dataset Iris từ Scikit-Learn, sau đó:
  1. Lọc các dòng có giá trị cột đầu tiên lớn hơn trung bình.
  2. Nhóm dữ liệu theo cột nhãn (`target`) và tính trung bình của các cột.
- **Hướng dẫn:** Sử dụng `df[df[col] > value]`, `groupby()`, và `mean()`.

In [ ]:
from sklearn import datasets

iris = datasets.load_iris()
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
## Tính trung bình cột đầu tiên
mean = np.mean(iris_df.iloc[:, 0]) ## iloc[] truy cập giá trị theo index, [dòng, cột]
print(mean)
## Lọc các dòng có giá trị cột đầu tiên lớn hơn trung bình
iris_df[iris_df.iloc[:, 0] > mean]

5.843333333333334


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
50                 7.0               3.2                4.7               1.4
51                 6.4               3.2                4.5               1.5
52                 6.9               3.1                4.9               1.5
54                 6.5               2.8                4.6               1.5
56                 6.3               3.3                4.7               1.6
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[70 rows x 4 columns]

In [ ]:
iris_df.groupby(iris.target).mean() ## Nhóm dữ liệu

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0              5.006             3.428              1.462             0.246
1              5.936             2.770              4.260             1.326
2              6.588             2.974              5.552             2.026

- **Pandas** có khá nhiều phương thức khác nhau nên để sử dụng nhuần nhuyễn có thể đọc thêm tài liệu và làm thêm các bài tập khác.

### Bài 7: Vẽ biểu đồ cơ bản
- **Yêu cầu:** Tạo dữ liệu giả lập với 10 điểm (x từ 0 đến 9, y là giá trị ngẫu nhiên từ 1 đến 10), sau đó:
  1. Vẽ biểu đồ đường và biểu đồ phân tán trên cùng một figure.
  2. Thêm tiêu đề, nhãn trục, và chú thích.
- **Hướng dẫn:** Sử dụng `plt.plot()`, `plt.scatter()`, `title()`, `xlabel()`, `ylabel()`, và `legend()`.

In [1]:
import matplotlib.pyplot as plt
import numpy as np

x = np.random.randint(0, 10, 10)
y = np.random.randint(1, 11, 10)
print(x, y)

[7 3 9 9 5 0 1 1 6 0] [6 8 4 4 9 7 8 7 4 8]


### Bài 8: Vẽ nhiều biểu đồ
- **Yêu cầu:** Sử dụng dataset Iris, vẽ 4 biểu đồ histogram cho 4 cột dữ liệu trên cùng một figure (sử dụng subplot).
- **Hướng dẫn:** Sử dụng `plt.subplot()` và `plt.hist()`.

### Bài 9: Vẽ biểu đồ hộp
- **Yêu cầu:** Sử dụng dataset Iris, vẽ biểu đồ hộp (boxplot) cho cột đầu tiên của dữ liệu.
- **Hướng dẫn:** Sử dụng `plt.boxplot()`.